
-- ============================================================
-- gimpo_seed_2026-09-14.sql
-- 김포시 지도(지도2) 신규 자료 29건 추가
-- D1 콘솔에서 이 파일 내용만 붙여넣고 실행하면 됩니다.
-- (schema.sql을 이미 실행했다면 다시 실행할 필요 없음 - 이 파일은 추가분만)
-- ============================================================

INSERT OR IGNORE INTO gimpo_incidents (id, dong, cause, title, desc, source, source_url, date) VALUES ('gimpo-seed-001', '고촌읍', 'habitat', '고촌읍 태리 개발사업 피해로 서식 환경 변화', '한국야생조류보호협회가 2023년 11월 15일 김포시 풍무동과 고촌읍 태리 일대에서 먹이활동을 하는 재두루미 2가족, 총 7개체를 확인했다. 재두루미가 김포평야를 찾아온 것은
김포 지역이 겨울철새의 중요한 서식·먹이터 역할을 하고 있다는 것을 보여준다.특히 김포평야의 농경지와 주변 환경이 재두루미가 먹이를 구하고 머무를 수 있는 공간으로 활용되고 있다. 따라서 개발이나 환경 변화가 이러한 서식 환경에 영향을 줄 경우 재두루미의 먹이활동과 서식에 피해가 발생할 가능성이 있다.', '김포신문', 'https://www.igimpo.com/news/articleView.html?idxno=80571', '2023-11-15');
INSERT OR IGNORE INTO gimpo_incidents (id, dong, cause, title, desc, source, source_url, date) VALUES ('gimpo-seed-002', '구래동', 'habitat', '한강신도시 개발로 훼손된 철새 서식지', '김포시가 한강조류생태공원에 ‘낱알들녘’이라는 야생조류용 경작지를 조성했다. 이곳은 벼를 수확하지 않고 일부 낱알을 남겨 겨울철새들이 먹이를 구할 수 있도록 만든 공간이다.
특히 겨울철 김포를 찾는 철새들의 먹이 부족 문제를 완화하고 서식 환경을 보호하기 위한 목적이 있다. 즉, 도시화와 농경지 감소 등으로 야생조류가 먹이를 구하기 어려워지는 문제에 대응하기 위한 사례로 볼 수 있다.', '경기신문', 'https://www.kgnews.co.kr/mobile/article.html?no=528447', '2018-10-07');
INSERT OR IGNORE INTO gimpo_incidents (id, dong, cause, title, desc, source, source_url, date) VALUES ('gimpo-seed-003', '걸포동', 'pollution', '수질 오염 및 하천 관리 문제로 물고기 약 2.6톤이 집단 폐사', '2020년 김포시 감정동 나진포천에서 물고기 약 2.6톤이 집단 폐사했다. 당시 하천의 수질 상태와 관리 문제가 원인으로 지적되면서, 하천 환경의 변화와 오염이 수생 생물의 생존에 직접적인 피해를 줄 수 있다.', '경기일보', 'https://www.kyeonggi.com/article/202010091140942', '2020-10-09');
INSERT OR IGNORE INTO gimpo_incidents (id, dong, cause, title, desc, source, source_url, date) VALUES ('gimpo-seed-004', '기타/미상', 'conflict', '김포시 전역, 반려견 유기로 인한 들개화 및 주민 안전 위협', '김포에서 들개가 출몰해 주민들의 불안과 안전 문제를 일으키고 있으며, 하루에도 여러 건의 관련 민원이 발생하고 있다. 기사에서는 들개가 발생하는 주요 원인 중 하나로 반려견 유기를 지적한다. 특히 재개발 지역에서 주민들이 키우던 개를 버리고 떠나면서, 유기견이 야생에서 생활하며 들개로 변하는 사례가 나타나고 있다.', '김포신문', 'https://www.igimpo.com/news/articleView.html?idxno=91373', '2025-12-31');
INSERT OR IGNORE INTO gimpo_incidents (id, dong, cause, title, desc, source, source_url, date) VALUES ('gimpo-seed-005', '기타/미상', 'conflict', '김포시, 입양 고양이 학대 및 살해 사건', '김포에서 입양한 고양이를 학대해 숨지게 한 사건이 발생했다. 이 사건은 반려동물을 입양한 뒤 적절하게 보호하지 않고 학대한 사례이다.', '연합뉴스tv', 'https://www.yonhapnewstv.co.kr/news/AKR20250729161635228', '2025-07-29');
INSERT OR IGNORE INTO gimpo_incidents (id, dong, cause, title, desc, source, source_url, date) VALUES ('gimpo-seed-006', '하성면', 'etc', '김포시 하성면, 독극물 살포 및 엽총 밀렵으로 인한 겨울 철새 집단 폐사', '김포시 하성면에서 겨울철새들이 집단으로 폐사하는 사건이 발생했다. 기사에서는 독극물 살포와 불법적인 밀렵 행위가 철새들의 피해 원인으로 지적됐다. 이는 사람의 불법적인 행동으로 인해 야생동물이 직접적인 피해를 입은 사례로, 야생동물에 대한 불법 포획과 유해물질 사용이 생태계에 피해를 줄 수 있음을 보여준다.', '경기일보', 'https://www.kyeonggi.com/article/201201310439025', '2012-01-31');
INSERT OR IGNORE INTO gimpo_incidents (id, dong, cause, title, desc, source, source_url, date) VALUES ('gimpo-seed-007', '양촌읍', 'conflict', '김포시 양곡리, 불법 도살 및 가혹한 환경 속 동물 방치·학대', '2021년 7월 10일, 동물구조119가 김포시 양곡리의 한 개 도살장을 조사하는 과정에서 불법 도살 정황과 열악한 사육환경을 확인했다. 현장에서는 도살에 사용된 도구와 개털 등이 발견됐으며, 도살장 옆에서는 12마리의 개가 뜬장에서 사육되고 있었다.', '한국일보', 'https://v.daum.net/v/20210722110003327?f=p', '2021-07-22');
INSERT OR IGNORE INTO gimpo_incidents (id, dong, cause, title, desc, source, source_url, date) VALUES ('gimpo-seed-008', '고촌읍', 'conflict', '김포시 고촌읍, 불법 사육장에서 개 방치', '김포시 고촌읍의 국유지를 무단으로 점유한 불법 개 사육장에서 110여 마리의 개가 발견됐다. 대부분의 개가 대소변이 쌓인 뜬장에서 사육되고 있었으며, 주변에는 30구가 넘는 개 사체도 방치된 상태였다. 일부 개에서는 심한 굶주림으로 인해 다른 개의 사체를 먹은 흔적도 확인됐다. 이후 동물보호단체 등이 약 100마리를 구조해 치료와 임시보호를 진행했다.', '연합뉴스', 'https://www.yna.co.kr/view/AKR20201211145900065  + https://youtu.be/h40TcSSkUEk?si=JlG7fuSNXmBO5qBd', '2020-12-11');
INSERT OR IGNORE INTO gimpo_incidents (id, dong, cause, title, desc, source, source_url, date) VALUES ('gimpo-seed-009', '풍무동', 'habitat', '김포시 풍무동, 도시개발 공사 강행으로 인한 멸종위기 맹꽁이 서식지 파괴 위기', '김포시 풍무동의 도시개발 사업 과정에서 멸종위기종인 맹꽁이의 서식지가 훼손될 위기에 놓였다는 내용이다. 개발사업이 진행되면서 맹꽁이가 서식하던 공간이 공사 대상에 포함되어, 도시개발과 야생동물 서식지 보전 사이의 갈등이 발생했다.', '인천일보', 'https://www.igimpo.com/news/articleView.html?idxno=80571', '2023-09-05');
INSERT OR IGNORE INTO gimpo_incidents (id, dong, cause, title, desc, source, source_url, date) VALUES ('gimpo-seed-010', '대곶면', 'pollution', '김포시 대곶면 거물대리, 유해물질 노출로 인한 기형 개구리 발견', '김포시 거물대리에서 공장들이 농경지 주변에 밀집하면서 환경오염 문제가 발생했다. 이 지역에서는 한쪽 눈과 다리에 이상이 있는 기형 개구리가 발견됐고, 농수로에서는 죽은 왜가리도 발견됐다. 환경부가 거물대리의 공장 86곳을 조사한 결과 62곳(약 72%)에서 환경법 위반이 확인됐다. 일부 공장에서는 대기 중 유해물질이 검출됐고, 중금속이 섞인 토양이나 폐기물이 제대로 관리되지 않거나 오·폐수가 농수로로 배출되는 문제도 확인됐다.', '노컷 뉴스', 'https://www.nocutnews.co.kr/news/4381719', '2015-03-12');
INSERT OR IGNORE INTO gimpo_incidents (id, dong, cause, title, desc, source, source_url, date) VALUES ('gimpo-seed-011', '사우동', 'pollution', '김포시 계양천, 물고기들이 침전물로 인해 산소 없어 집단 폐사', '2017년 7월 7일 오후, 김포시 계양천에서 수백 마리의 물고기가 배를 드러낸 채 떠오르는 집단 폐사 현상이 발생했다. 김포시환경관리사업소가 현장을 조사한 결과, 용존산소량(DO)이 0.24ppm으로 측정됐다. 물고기가 생존하기 위해 필요한 DO가 약 5ppm이라는 점에서 매우 낮은 수치였다. 김포시환경관리사업소는 많은 비가 예상되면서 운양배수펌프장에서 물을 빼낸 뒤, 바닥에 쌓여 있던 침전물이 물과 섞이면서 발생한 현상으로 설명했다. 폐사한 물고기 떼는 현장에서 모두 수거·폐기 처리됐다.', '씨티21뉴스', 'http://www.city21.co.kr/news/articleView.html?idxno=24335', '2017-07-07');
INSERT OR IGNORE INTO gimpo_incidents (id, dong, cause, title, desc, source, source_url, date) VALUES ('gimpo-seed-012', '양촌읍', 'etc', '김포시 양촌읍, 무허가 건축물 행정처분으로 인한 보호 유기견 거처 상실 위기', '김포시 양촌읍의 민간 유기견 보호시설 ‘아지네마을’에서 유기견 200여 마리를 보호하고 있었지만, 시설의 건축물 16개 동(총 911㎡)이 무허가 건축물로 확인됐다. 이에 양촌읍행정복지센터가 원상복구 시정명령 사전 통지를 했다.시설이 철거될 경우 보호 중인 200여 마리가 갈 곳이 없어질 수 있다는 점 때문에 시설 측과 동물보호 활동가들이 선처를 호소했다. 경기도는 유기견들을 다른 시설로 옮길 방안을 검토했고, 김포시 측은 원상복구와 이주 계획에 따라 행정처분 시점을 협의할 수 있다는 입장을 밝혔다.', '연합뉴스', 'https://www.yna.co.kr/view/AKR20210210103000065', '2021-02-12');
INSERT OR IGNORE INTO gimpo_incidents (id, dong, cause, title, desc, source, source_url, date) VALUES ('gimpo-seed-013', '하성면', 'etc', '김포시 하성면 돼지열병(ASF)', '2022년 9월 김포시 하성면의 한 양돈농장에서 아프리카돼지열병(ASF)이 발생하면서 방역 당국이 확산을 막기 위한 조치를 진행했다. 김포에서는 3년 만에 ASF가 다시 발생했으며, 감염 농장 주변의 돼지들을 살처분하는 등 방역 조치가 이루어졌다.', '최신신문', 'https://www.yna.co.kr/view/AKR20220929094700065?utm_source=chatgpt.com', '2022-09-29');
INSERT OR IGNORE INTO gimpo_incidents (id, dong, cause, title, desc, source, source_url, date) VALUES ('gimpo-seed-014', '대곶면', 'collision', '김포 초지대교~인천 구간 투명방음벽', '경기도는 투명방음벽 등에 야생조류가 충돌해 죽는 사고를 줄이기 위해 조류충돌 예방정책을 추진했다. 당시 김포 초지대교~인천 구간을 포함한 신설 도로 3곳의 투명방음벽에 조류충돌 방지시설을 전면적으로 설치할 계획이라고 밝혔다.', '경기도 뉴스포털', 'https://gnews.gg.go.kr/news/news_detail.do?number=202103030953277770C048&s_code=C048&utm_source=chatgpt.com.', '2021-03-05');
INSERT OR IGNORE INTO gimpo_incidents (id, dong, cause, title, desc, source, source_url, date) VALUES ('gimpo-seed-015', '하성면', 'habitat', '김포시 하성면 후평리.   농수로 보강공사와 제2외곽순환도로 착공 등의 영향으로 안착하는 재두루미가 급감', '김포시는 하성면 후평리에서 2010년부터 재두루미 취·서식지 보전사업을 추진하고 있다고 밝혔다. 2018년에는 177마리, 2019년에는 181마리가 관찰됐지만, 2020년부터 농수로 보강공사와 제2외곽순환도로 착공 등의 영향으로 안착하는 재두루미 개체 수가 급감했다. 2021년에는 사업부지 모니터링에서 재두루미 87개체가 확인됐다.', '김포시 뉴스포털', 'https://www.gimpo.go.kr/news/selectBbsNttView.do?bbsNo=466&key=9377&nttNo=717162&pageIndex=9&pageUnit=10&searchCnd=all&searchKrwd=%EA%B2%A8%EC%9A%B8%EC%B2%A0&utm_source=chatgpt.com', '2023-02-13');
INSERT OR IGNORE INTO gimpo_incidents (id, dong, cause, title, desc, source, source_url, date) VALUES ('gimpo-seed-016', '고촌읍', 'conflict', '불법 사육·도살 및 보호시설 부족으로 인한 안락사 위기', '동물구조119가 신고를 받고 김포시 고촌읍의 한 야산에 있던 불법 개 도살장을 발견하고 개 23마리를 구조했다. 구조된 개들은 대부분 어린 개였으며, 이후 일부는 입양됐지만 18마리는 입양자를 찾지 못해 안락사 위기에 놓였다. 동물구조단체는 유기견을 보호할 시설과 예산이 부족해 민간단체만으로는 해결하기 어렵다며 지방자치단체와 정부의 지원 확대가 필요하다고 지적했다.', '연합뉴스', 'https://v.daum.net/v/3KaacZ2mh7?utm_source=chatgpt.com', '2022-07-22');
INSERT OR IGNORE INTO gimpo_incidents (id, dong, cause, title, desc, source, source_url, date) VALUES ('gimpo-seed-017', '고촌읍', 'habitat', '김포시 고촌읍 신곡리 돌방구지 일대. 간척·개발 사업이 진행되면서 재두루미의개체 수가 크게 감소', '김포시 고촌읍 신곡리 돌방구지 일대는 재두루미가 찾아오는 지역이었지만, 간척과 개발 사업이 진행되면서 재두루미가 안정적으로 머물 수 있는 서식·먹이 환경이 변화했고 개체 수가 크게 감소했다.', '연합뉴스', 'https://www.yna.co.kr/view/AKR20260303034800065?utm_source=chatgpt.com', '2026-03-03');
INSERT OR IGNORE INTO gimpo_incidents (id, dong, cause, title, desc, source, source_url, date) VALUES ('gimpo-seed-018', '양촌읍', 'conflict', '김포시 양촌읍 강아지 학대', '2024년 3월 2일 김포시 양촌읍 공원 인근에서 학대를 당한 것으로 추정되는 강아지가 발견되어 구조됐다. 동물보호단체는 강아지에게 여러 신체적 손상이 발견되어 학대가 의심된다며 가해자를 고발했고, 김포경찰서는 주변 CCTV와 차량 블랙박스 등을 확인하며 실제 학대 행위가 있었는지 수사했다.', 'YTN', 'https://m.ytn.co.kr/news_view.php?key=202403112317284288&pos=&s_mcd=0103', '2024-03-11');
INSERT OR IGNORE INTO gimpo_incidents (id, dong, cause, title, desc, source, source_url, date) VALUES ('gimpo-seed-019', '풍무동', 'etc', '김포시 풍무동의 동물 판매업체에서 화재가 발생해 사육 중이던 도마뱀 50마리가 폐사', '김포시 풍무동의 한 상가건물에서 화재가 발생하면서 동물 판매업체에서 사육하던 도마뱀 50마리가 폐사했다. 화재로 인한 인명 피해는 없었으며, 사육시설 일부가 불에 탔다. 소방 당국은 전기적 요인에 의해 화재가 발생한 것으로 보고 정확한 원인을 조사하고 있다.', '경기일보', 'https://naver.me/xKyJ1DYz', '2026-04-02');
INSERT OR IGNORE INTO gimpo_incidents (id, dong, cause, title, desc, source, source_url, date) VALUES ('gimpo-seed-020', '기타/미상', 'conflict', '김포시 입양 고양이 상습 학대 의혹', '김포에서 여러 마리의 고양이를 입양한 사람이 고양이들을 상습적으로 학대한 혐의로 경찰 조사를 받고 있는 사례이다. 동물보호단체의 신고를 계기로 수사가 시작되었으며, 경찰이 실제 학대 여부를 조사하고 있다.', '한국경제TV', 'https://naver.me/5CCylYVA', '2025-07-29');
INSERT OR IGNORE INTO gimpo_incidents (id, dong, cause, title, desc, source, source_url, date) VALUES ('gimpo-seed-021', '하성면', 'habitat', '서식지 훼손·생태환경 악화 우려', '하동천은 생태적 가치가 높은 지역이지만 생물서식지를 지속적으로 보전·복원할 필요성이 있어 김포시가 생태복원 계획을 수립했다. 특히 금개구리 서식지, 물새 쉼터, 큰기러기 먹이터 등을 조성하고 생물다양성을 높이기 위한 복원사업을 추진했다. 2025년까지 단계적으로 복원하고 지속적인 모니터링을 실시할 계획이라고 밝혔다', '김포시 뉴스포털', 'https://m.gimpo.go.kr/news/selectBbsNttView.do?bbsNo=466&key=9377&nttNo=643035&pageIndex=99&pageUnit=10&searchCnd=all&searchKrwd=%EA%B3%B5%EC%9B%90&utm_source=chatgpt.com', '2022-09-02');
INSERT OR IGNORE INTO gimpo_incidents (id, dong, cause, title, desc, source, source_url, date) VALUES ('gimpo-seed-022', '하성면', 'etc', '김포에서 다친 흰꼬리수리 구조·치료', '김포시 하성면에서 발견된 천연기념물 흰꼬리수리가 구조되어 치료를 받은 뒤 자연으로 돌아갔다. 약 1년간 치료를 받은 후 파주에서 방사됐으며, 이동경로 확인을 위해 위치추적기를 부착했다.', '연합뉴스', 'https://www.yna.co.kr/view/AKR20160310064700005?utm_source=chatgpt.com', '2016-03-10');
INSERT OR IGNORE INTO gimpo_incidents (id, dong, cause, title, desc, source, source_url, date) VALUES ('gimpo-seed-023', '기타/미상', 'etc', '김포 하천변 기러기 폐사', '김포의 한 하천변에서 기러기 5마리가 폐사한 채 발견됐다. 조류인플루엔자(AI) 감염 가능성을 확인하기 위해 정밀검사를 실시했으며, AI 감염 여부를 조사했다.', '김포신문', 'https://www.igimpo.com/news/articleView.html?idxno=35111&utm_source=chatgpt.com', '2024-01-23');
INSERT OR IGNORE INTO gimpo_incidents (id, dong, cause, title, desc, source, source_url, date) VALUES ('gimpo-seed-024', '통진읍', 'etc', '김포 양돈농장 아프리카돼지열병(ASF) 발생', '김포의 한 돼지농장에서 돼지 9마리가 폐사한 뒤 정밀검사를 실시한 결과 **아프리카돼지열병(ASF)**이 확인됐다. 확산을 막기 위해 해당 농장과 인접 농장의 돼지에 대한 방역 조치와 살처분이 진행됐다.', '연합뉴스', 'https://www.yna.co.kr/view/AKR20230122029700003?utm_source=chatgpt.com', '2023-01-22');
INSERT OR IGNORE INTO gimpo_incidents (id, dong, cause, title, desc, source, source_url, date) VALUES ('gimpo-seed-025', '기타/미상', 'etc', '김포 산란계 농장 조류인플루엔자 발생', '김포시의 한 산란계 농장에서 H5형 AI 항원이 확인됐고, 이후 고병원성 AI 발생으로 확인됐다. 해당 농장에서 사육하던 닭 7만 5천여 마리를 살처분하고, 확산 방지를 위해 농장 출입 제한과 역학조사, 주변 지역 이동중지 등의 방역 조치가 실시됐다.', '연합뉴스', 'https://www.igimpo.com/news/articleView.html?idxno=80571', '2024-12-20');
INSERT OR IGNORE INTO gimpo_incidents (id, dong, cause, title, desc, source, source_url, date) VALUES ('gimpo-seed-026', '통진읍', 'habitat', '통진읍 수참리 도로 건설로 인한 멸종위기 양서류 서식환경 문제', '공사 현장에서 멸종위기종인 수원청개구리와 금개구리가 발견되면서 공사가 영향을 받았고, 보호를 위해 인근 지역으로 이주시키는 방안이 추진됐음. 주민들은 맹꽁이와 철새의 서식환경에도 영향을 줄 수 있다고 문제를 제기했다.', '브릿지경제', 'https://www.viva100.com/20200720010003844', '2020-07-20');
INSERT OR IGNORE INTO gimpo_incidents (id, dong, cause, title, desc, source, source_url, date) VALUES ('gimpo-seed-027', '기타/미상', 'etc', '김포 양계장 화재', '김포의 한 양계장에서 화재가 발생해 닭 2만6천 마리가 폐사한 것으로 보도됐다.', '경기일보', 'https://www.kyeonggi.com/article/20251128580013?utm_source=chatgpt.com', '2025-11-28');
INSERT OR IGNORE INTO gimpo_incidents (id, dong, cause, title, desc, source, source_url, date) VALUES ('gimpo-seed-028', '월곶면', 'etc', '월곶면 돼지축사 화재', '월곶면의 한 돼지축사에서 화재가 발생했다는 신고가 접수됐고, 소방당국이 출동해 화재 진압에 나섰다. 이 화재로 축사에서 사육 중이던 돼지 약 100마리가 폐사한 것으로 보도됐다.', '중앙신문', 'https://www.jasm.co.kr/news/articleView.html?idxno=192002&utm_source=chatgpt.com', '2025-12-29');
INSERT OR IGNORE INTO gimpo_incidents (id, dong, cause, title, desc, source, source_url, date) VALUES ('gimpo-seed-029', '기타/미상', 'etc', '김포 구조견 안락사·자연사', '김포신문은 김포에서 발생한 유실·유기견의 보호 실태를 조사했다. 2023년부터 2025년 11월까지 김포에서 해당 보호소로 보내진 개는 2,856마리였으며, 이 중 약 76%가 자연사 또는 안락사로 사망한 것으로 나타났다. 반면 입양되거나 원래 주인에게 돌아간 경우는 371마리였다.', '김포신문', 'https://www.igimpo.com/news/articleView.html?idxno=80571', '2026-01-07');
